SPEL/SPEL.Medewerkers/Controllers/BetalingController.cs
using SPEL.Domain.Abstract;
using SPEL.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SPEL.Medewerkers.Models;


namespace SPEL.Medewerkers.Controllers
{
    public class BetalingController : Controller
    {
        private IRepository<Inschrijving> inschrijvingen;
        private IRepository<Lid> leden;
        private IRepository<Sportklasse> klasses;
        private IRepository<BetalingType> betalingTypes;
        private IRepository<Betaling> betalingen;
        private Betaling betaald;
        private BetalingType betalingType;

        public BetalingController(IRepository<Inschrijving> a_repo, IRepository<Lid> b_repo, IRepository<Sportklasse> c_repo, IRepository<Betaling> d_repo, IRepository<BetalingType> e_repo )
        {
            inschrijvingen = a_repo;
            leden = b_repo;
            klasses = c_repo;
            betalingTypes = e_repo;
            betalingen = d_repo;
        }

        // GET: Betaling
        [HttpGet]
        public ActionResult Index()
        {
            if (betalingen == null)
            {
                return View("GeenBetalingen");
            }
            else if (betalingen.List.Count() == 0)
            {
                return View("GeenBetalingen");
            }
            else 
            {
                return View(betalingen.List);
            }

            
        }
        [HttpPost]
        public ActionResult Index(Betaling betaling)
        {
            BetaalViewModel betalen = new BetaalViewModel();
            betalen = new BetaalViewModel
            {
                betaaldeRekeningen = (from v in betalingen.List where v.Betaald.Equals(betaling.Betaald) select v)
            };

            return View(betalen.betaaldeRekeningen);
        }

        public ActionResult Factuur()
        {

            var model = new PrintenViewModel();
            var alleBetalingen = betalingen.GetAll(b => b.Lid);
            alleBetalingen = alleBetalingen.Where(b => b.Betaald == false);
            var alleInschrijvingen = inschrijvingen.GetAll(v => v.sportklasse, v => v.lid);
            model.inschrijvingen = alleInschrijvingen.ToList();
            List<Lid> alleLeden = new List<Lid>();
            foreach (Betaling betaling in alleBetalingen)
            {
                if (alleLeden.Contains(betaling.Lid))
                {

                }
                else
                {
                    alleLeden.Add(betaling.Lid);
                }
            }
            model.leden = alleLeden;
            model.betaling = alleBetalingen.ToList();



            return new Rotativa.ViewAsPdf("Factuur", model) { FileName = "AlleFacturen.pdf" };

        }

        public ActionResult FactuurK()
        {
            var model = new PrintenViewModel();
            var alleBetalingen = betalingen.GetAll(b => b.Lid);
            alleBetalingen = alleBetalingen.Where(b => b.Betaald == false);
            var alleInschrijvingen = inschrijvingen.GetAll(v => v.sportklasse, v => v.lid);
            model.inschrijvingen = alleInschrijvingen.ToList();
            List<Lid> alleLeden = new List<Lid>();
            foreach (Betaling betaling in alleBetalingen)
            {
                if (alleLeden.Contains(betaling.Lid))
                {

                }
                else
                {
                    alleLeden.Add(betaling.Lid);
                }
            }
            model.leden = alleLeden;
            model.betaling = alleBetalingen.ToList();
            return new Rotativa.ViewAsPdf("FactuurK", model) { FileName = "AlleFacturenKwartaal.pdf" };

        }

        public ActionResult FactuurJ()
        {
            var model = new PrintenViewModel();
            var alleBetalingen = betalingen.GetAll(b => b.Lid);
            alleBetalingen = alleBetalingen.Where(b => b.Betaald == false);
            var alleInschrijvingen = inschrijvingen.GetAll(v => v.sportklasse, v => v.lid);
            model.inschrijvingen = alleInschrijvingen.ToList();
            List<Lid> alleLeden = new List<Lid>();
            foreach (Betaling betaling in alleBetalingen)
            {
                if (alleLeden.Contains(betaling.Lid))
                {

                }
                else
                {
                    alleLeden.Add(betaling.Lid);
                }
            }
            model.leden = alleLeden;
            model.betaling = alleBetalingen.ToList();
            return new Rotativa.ViewAsPdf("FactuurJ", model) { FileName = "AlleFacturenJaar.pdf" };

        }

        [ActionName("EenFactuur")]
        public ActionResult Factuur(int id)
        {
            var model = new PrintenViewModel();
            model.leden = new List<Lid>();
            model.leden.Add(leden.FindById(id));
            var inschrijvingenLid = inschrijvingen.GetAll(v => v.sportklasse, v => v.lid).Where(v => v.lidId == id);
            model.inschrijvingen = inschrijvingenLid.ToList();
            model.betaling = betalingen.List.ToList().Where(b => b.Betaald == false).ToList();



            return new Rotativa.ViewAsPdf("Factuur", model) { FileName = "Factuur.pfd" };


        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
    }
            Betaling betaling = betalingen.FindById((int)id);
            if (betaling == null)
            {
                return HttpNotFound();
            }
            return View(betaling);
        }

        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Betaling betaling = betalingen.FindById((int)id);
            if (betaling == null)
            {
                return HttpNotFound();
            }
            return View(betaling);
        }

        // POST: inschrijvings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Betaling betaling)
        {



            if (ModelState.IsValid)
            {
                betalingen.Update(betaling);
                return RedirectToAction("Index");
            }
            return View(betaling);
        }
    }

}

SPEL/SPEL.Medewerkers/Controllers/LedenController.cs
using SPEL.Domain.Abstract;
using SPEL.Domain.Concrete;
using SPEL.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rotativa;
using SPEL.Medewerkers.Models;

namespace SPEL.Medewerkers.Controllers
{
    public class LedenController : Controller
    {
        
        private IRepository<Lid> repository;
        private IRepository<Inschrijving> r_inschrijvingen;
        private IRepository<Sport> r_sporten;
        private IRepository<Sportklasse> r_klasses;
        private Lid bestaandlid;

        public LedenController(IRepository<Lid> repository, IRepository<Inschrijving> i_repo, IRepository<Sport> i_sporten, IRepository<Sportklasse> i_klasses)
        {
            this.repository = repository;
            this.r_inschrijvingen = i_repo;
            r_sporten = i_sporten;
            r_klasses = i_klasses;
        }

        [Authorize]
        // GET: Home
        [HttpGet]
        public ActionResult LidToevoegen()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LidToevoegen(Lid lid, HttpPostedFileBase image = null)
        {
          LidViewModel emailcheck = new LidViewModel();
          emailcheck = new LidViewModel
          {
            leden = repository.List.Where(x => x.Email.Equals(lid.Email))
          };

          if (emailcheck.leden.Count() == 0)
          {
              LidViewModel lidview = new LidViewModel();
              lidview = new LidViewModel
              {
                  leden = repository.List.Where(x => x.Naam.Equals(lid.Naam))
              };
              if (lidview.leden.Count() == 0)
              {
                  if (ModelState.IsValid)
                  {
                      if (image != null)
                      {
                          lid.ImageMimeType = image.ContentType;
                          lid.ImageData = new byte[image.ContentLength];
                          image.InputStream.Read(lid.ImageData, 0, image.ContentLength);
                      }
                      repository.Add(lid);
                      return View("Toegevoegd", lid);
                  }

                  return View(lid);
              }
              else
              {
                  return View("AlToegevoegd", lid);
              }
          }

          else
          {
              return View("EmailAdresBestaatAl", lid);
          }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LidAlsnogtoevoegen(Lid lid, HttpPostedFileBase image = null)
        {

                if (ModelState.IsValid)
                {
                    if (image != null)
                    {
                        lid.ImageMimeType = image.ContentType;
                        lid.ImageData = new byte[image.ContentLength];
                        image.InputStream.Read(lid.ImageData, 0, image.ContentLength);
                    }
                    repository.Add(lid);
                    return View("Toegevoegd", lid);
                }

                return View(lid);
            

        }

        public ActionResult AlToegevoegd(Lid lid)
        {
            LidViewModel lidview = new LidViewModel();
            lidview = new LidViewModel
            {
                leden = repository.List.Where(x => x.ID == lid.ID)
            };
            bestaandlid = lidview.leden.First();
            return View(bestaandlid);
        }

        public FileContentResult GetImage(int ID)
        {
            Lid lid = repository.List.FirstOrDefault(p => p.ID == ID);
            if (lid.ImageMimeType != null)
            {
                return File(lid.ImageData, lid.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult LedenBeheer ()
        {

            return View(repository.List);
        }

        public ActionResult Sportkaart()
        {
            var model = getAllePrint();

            
            return new Rotativa.ViewAsPdf("Sportkaart", model) { FileName = "AlleSportkaarten.pdf" };
        }

        [ActionName("EenSportKaart")]
        public ActionResult Sportkaart(int id)
        {
            var model = getByIdPrint(id);

            return new Rotativa.ViewAsPdf("Sportkaart", model) { FileName = "sportkaart.pfd" };
        }

        public PrintenViewModel getByIdPrint(int id)
        {
            var model = new PrintenViewModel();
            model.leden = repository.List.Where(i => i.ID == id).ToList();
            model.inschrijvingen = (r_inschrijvingen.List.Where(k => k.lidId == id).ToList());
            model.klasses = r_klasses.List.ToList();
            return model;
        }

        public PrintenViewModel getAllePrint()
        {
            var model = new PrintenViewModel();
            var alleActieveInschrijvingen = r_inschrijvingen.GetAll(k => k.sportklasse, k => k.lid).Where(k => k.datumUitschrijving == null || k.datumUitschrijving > DateTime.Today);
            List<Lid> ledenActief = new List<Lid>();
            foreach(Inschrijving ins in alleActieveInschrijvingen){
                if (ledenActief.Contains(ins.lid))
                {

                }
                else
                {
                    ledenActief.Add(ins.lid);
                }
            }
            model.leden = ledenActief;
            model.inschrijvingen = alleActieveInschrijvingen.ToList();
            model.klasses = r_klasses.GetAll(k => k.sport).ToList();
            return model;
        }
    }
}

SPEL/SPEL.Medewerkers/Views/Betaling/Details.cshtml
@model SPEL.Domain.Entities.Betaling

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Inschrijving</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lid.Naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lid.Naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lid.Pasfoto)
        </dt>

        <dd>
            <img class="img-thumbnail" width="150" height="150" src="@Url.Action("GetImage", "Leden",
               new { Model.Lid.ID })" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lid.GebDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lid.GebDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lid.Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lid.Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bedrag)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bedrag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BetalingType.BetalingTypeNaam)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BetalingType.BetalingTypeNaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Betaald)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Betaald)
        </dd>

    </dl>
</div   >
<p>
    @Html.ActionLink("Print Factuur", "EenFactuur", new { id = Model.ID}) |
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SPEL/SPEL.Medewerkers/Views/Betaling/Edit.cshtml
@model SPEL.Domain.Entities.Betaling

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inschrijving</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Bedrag)
        @Html.HiddenFor(model => model.BetalingTypeID)
        @Html.HiddenFor(model => model.LidID)

        <div class="form-group">
            @Html.LabelFor(model => model.Betaald, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Betaald, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Betaald, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SPEL/SPEL.Medewerkers/Views/Betaling/Factuur.cshtml
@model SPEL.Medewerkers.Models.PrintenViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Sportkaarten</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- jQuery UI CSS Reference -->
    <link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" />
    <!-- Required jQuery and jQuery UI Javascript references -->
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.4.min.js")"></script>
</head>
<body>
    <div class="container" style="width : 50%">
        @if (Model.leden.Count == 0)
        {
            <h1>Alle facturen zijn betaald.</h1>
        }
        @foreach (var lid in Model.leden)
        {
            <div class="jumbotron" style="background-color : bisque">
                <h1>@lid.Naam</h1>
                <div class="row">
                    <div class="col-xs-6">
                        <h3>Gegevens</h3>
                        <ul class="list-group">
                            <li class="list-group-item">Geboortedatum: @lid.GebDatum.Date.ToShortDateString()</li>
                            <li class="list-group-item">Geslacht: @lid.Geslacht</li>
                            <li class="list-group-item">Adres: @lid.Adres</li>
                        </ul>
                    </div>
                    <div class="col-xs-6">
                        <h3>Inschrijvingen</h3>
                        <ul class="list-group">
                            @foreach (var inschrijving in Model.inschrijvingen)
                            {
                                if (inschrijving.lidId == lid.ID && (inschrijving.datumUitschrijving == null || inschrijving.datumUitschrijving > DateTime.Today))
                                {
                                    <li class="list-group-item">Sportklasse : @inschrijving.sportklasse.naam</li>
                                }

                            }
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-10">
                        <h3> Factuur</h3>
                        <ul class="list-group">
                            @foreach (var factuur in Model.betaling)
                            {
                                if (factuur.LidID == lid.ID)
                                {
                                    <li class="list-group-item">TotaalBedrag Incl. 21% BTW: @factuur.Bedrag</li>
                                    var exBtw = @factuur.Bedrag / 121 * 100m;
                                    <li class="list-group-item">TotaalBedrag Excl. 21% BTW: @exBtw.ToString("N") </li>
                                }
                            }

                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

SPEL/SPEL.Medewerkers/Views/Betaling/FactuurJ.cshtml
@model SPEL.Medewerkers.Models.PrintenViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Sportkaarten</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- jQuery UI CSS Reference -->
    <link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" />
    <!-- Required jQuery and jQuery UI Javascript references -->
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.4.min.js")"></script>
</head>
<body>
    <div class="container" style="width : 50%">
        @if (Model.leden.Count == 0)
        {
            <h1>Alle facturen zijn betaald.</h1>
        }
        @foreach (var lid in Model.leden)
        {
            <div class="jumbotron" style="background-color : bisque">
                <h1>@lid.Naam</h1>
                <div class="row">
                    <div class="col-xs-6">
                        <h3>Gegevens</h3>
                        <ul class="list-group">
                            <li class="list-group-item">Geboortedatum: @lid.GebDatum.Date.ToShortDateString()</li>
                            <li class="list-group-item">Geslacht: @lid.Geslacht</li>
                            <li class="list-group-item">Adres: @lid.Adres</li>
                        </ul>
                    </div>
                    <div class="col-xs-6">
                        <h3>Inschrijvingen</h3>
                        <ul class="list-group">
                            @foreach (var inschrijving in Model.inschrijvingen)
                            {
                                if (inschrijving.lidId == lid.ID && (inschrijving.datumUitschrijving == null || inschrijving.datumUitschrijving > DateTime.Today))
                                {
                                    <li class="list-group-item">Sportklasse : @inschrijving.sportklasse.naam</li>
                                }

                            }
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-10">
                        <h3> Factuur</h3>
                        <ul class="list-group">
                            @foreach (var factuur in Model.betaling)
                            {
                                if (factuur.LidID == lid.ID)
                                {
                                    var bedrag = @factuur.Bedrag * 12m;
                                    <li class="list-group-item">TotaalBedrag Incl. 21% BTW: @bedrag.ToString("N")</li>
                                    var exBtw = @factuur.Bedrag / 121 * 100 * 12m;
                                    <li class="list-group-item">TotaalBedrag Excl. 21% BTW: @exBtw.ToString("N") </li>
                                }
                            }

                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

SPEL/SPEL.Medewerkers/Views/Betaling/FactuurK.cshtml
@model SPEL.Medewerkers.Models.PrintenViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Sportkaarten</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- jQuery UI CSS Reference -->
    <link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" />
    <!-- Required jQuery and jQuery UI Javascript references -->
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.4.min.js")"></script>
</head>
<body>
    <div class="container" style="width : 50%">
        @if (Model.leden.Count == 0)
        {
            <h1>Alle facturen zijn betaald.</h1>
        }
        @foreach (var lid in Model.leden)
        {
            <div class="jumbotron" style="background-color : bisque">
                <h1>@lid.Naam</h1>
                <div class="row">
                    <div class="col-xs-6">
                        <h3>Gegevens</h3>
                        <ul class="list-group">
                            <li class="list-group-item">Geboortedatum: @lid.GebDatum.Date.ToShortDateString()</li>
                            <li class="list-group-item">Geslacht: @lid.Geslacht</li>
                            <li class="list-group-item">Adres: @lid.Adres</li>
                        </ul>
                    </div>
                    <div class="col-xs-6">
                        <h3>Inschrijvingen</h3>
                        <ul class="list-group">
                            @foreach (var inschrijving in Model.inschrijvingen)
                            {
                                if (inschrijving.lidId == lid.ID && (inschrijving.datumUitschrijving == null || inschrijving.datumUitschrijving > DateTime.Today))
                                {
                                    <li class="list-group-item">Sportklasse : @inschrijving.sportklasse.naam</li>
                                }

                            }
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-10">
                        <h3> Factuur</h3>
                        <ul class="list-group">
                            @foreach (var factuur in Model.betaling)
                            {
                                if (factuur.LidID == lid.ID)
                                {
                                    var bedrag = @factuur.Bedrag * 3m;
                                    <li class="list-group-item">TotaalBedrag Incl. 21% BTW: @bedrag.ToString("N")</li>
                                    var exBtw = @factuur.Bedrag / 121 * 100 *3m;
                                    <li class="list-group-item">TotaalBedrag Excl. 21% BTW: @exBtw.ToString("N") </li>
                                }
                            }

                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

SPEL/SPEL.Medewerkers/Views/Betaling/GeenBetalingen.cshtml
@{
    ViewBag.Title = "GeenBetalingen";
}

<h2>Er zijn nog geen facturen</h2>

SPEL/SPEL.Medewerkers/Views/Betaling/Index.cshtml
@model IEnumerable<SPEL.Domain.Entities.Betaling>
@{
    ViewBag.Title = "Betaling";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @using (Html.BeginForm())
{
       <p>Betaald: @Html.EditorFor(model => model.First().Betaald)</p>
        <input type="submit" value="Filter" class="btn btn-default" />
}
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Lid.Naam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BetalingType.BetalingTypeNaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bedrag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Betaald)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Lid.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BetalingType.BetalingTypeNaam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bedrag)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Betaald)
            </td>
            <td>
                @if (item.Betaald == false) {
                @Html.ActionLink("Print Factuur", "EenFactuur", new { id = item.ID})
                }|
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID })
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Print Alle Facturen Maand", "Factuur", " ", htmlAttributes: new { @class = "btn btn-default" })
@Html.ActionLink("Print Alle Facturen Kwartaal", "FactuurK", " ", htmlAttributes: new { @class = "btn btn-default" })
@Html.ActionLink("Print Alle Facturen Jaar", "FactuurJ", " ", htmlAttributes: new { @class = "btn btn-default" })